<a href="https://colab.research.google.com/github/kavithabantupalli/Machine-learning-project/blob/main/Product_Reviews_Prediction_with_Multinomial_Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Women Cloth Reviews Prediction with Multi Nomial Naive Bayes**

The multinomial Navie Bayes classifier is suitable for classification with discrete features(eg: word counts for text classification ).The multinomial distribution normally requires integer feature counts.However,in practice,fractional counts such as tf-idf may also work

**Import** **Library**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**Import** **Dataset**

In [ ]:
df=pd.read_csv('/content/sample_data/Womens Clothing E-Commerce Reviews.csv')

In [ ]:
df

ID  Clothing ID  Age  \
0          0          767   33   
1          1         1080   34   
2          2         1077   60   
3          3         1049   50   
4          4          847   47   
...      ...          ...  ...   
23481  23481         1104   34   
23482  23482          862   48   
23483  23483         1104   31   
23484  23484         1084   28   
23485  23485         1104   52   

                                                   Title  \
0                                                    NaN   
1                                                    NaN   
2                                Some major design flaws   
3                                       My favorite buy!   
4                                       Flattering shirt   
...                                                  ...   
23481                     Great dress for many occasions   
23482                         Wish it was made of cotton   
23483                              Cute, but see through   
23484  Very cute dress, perfect for summer parties an...   
23485                    Please make more like this one!   

                                             Review Text  Rating  \
0      Absolutely wonderful - silky and sexy and comf...       4   
1      Love this dress!  it's sooo pretty.  i happene...       5   
2      I had such high hopes for this dress and reall...       3   
3      I love, love, love this jumpsuit. it's fun, fl...       5   
4      This shirt is very flattering to all due to th...       5   
...                                                  ...     ...   
23481  I was very happy to snag this dress at such a ...       5   
23482  It reminds me of maternity clothes. soft, stre...       3   
23483  This fit well, but the top was very see throug...       3   
23484  I bought this dress for a wedding i have this ...       3   
23485  This dress in a lovely platinum is feminine an...       5   

       Recommended IND  Positive Feedback Count   Division Name  \
0                    1                        0       Initmates   
1                    1                        4         General   
2                    0                        0         General   
3                    1                        0  General Petite   
4                    1                        6         General   
...                ...                      ...             ...   
23481                1                        0  General Petite   
23482                1                        0  General Petite   
23483                0                        1  General Petite   
23484                1                        2         General   
23485                1                       22  General Petite   

      Department Name Class Name  
0            Intimate  Intimates  
1             Dresses    Dresses  
2             Dresses    Dresses  
3             Bottoms      Pants  
4                Tops    Blouses  
...               ...        ...  
23481         Dresses    Dresses  
23482            Tops      Knits  
23483         Dresses    Dresses  
23484         Dresses    Dresses  
23485         Dresses    Dresses  

[23486 rows x 11 columns]

In [ ]:
df.head()

ID  Clothing ID  Age                    Title  \
0   0          767   33                      NaN   
1   1         1080   34                      NaN   
2   2         1077   60  Some major design flaws   
3   3         1049   50         My favorite buy!   
4   4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   ID                       23486 non-null  int64 
 1   Clothing ID              23486 non-null  int64 
 2   Age                      23486 non-null  int64 
 3   Title                    19676 non-null  object
 4   Review Text              22641 non-null  object
 5   Rating                   23486 non-null  int64 
 6   Recommended IND          23486 non-null  int64 
 7   Positive Feedback Count  23486 non-null  int64 
 8   Division Name            23472 non-null  object
 9   Department Name          23472 non-null  object
 10  Class Name               23472 non-null  object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB


In [ ]:
df.shape

(23486, 11)

**Missing Values**

**Remove missing values in Reviews columns with No Review text**

In [ ]:
df.isna().sum()

ID                            0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [ ]:
df.isna().sum()

ID                            0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                   0
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [ ]:
df['Review Text']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review Text, Length: 23486, dtype: object

**Define Target(y) and Feature(X)**

In [ ]:
df.columns

Index(['ID', 'Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

In [ ]:
x=df['Review Text']

In [ ]:
y=df['Rating']

In [ ]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

**Train Test split**

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test =train_test_split(x,y,train_size=0.7,stratify=y,random_state=2529)

In [ ]:
x_train.shape, x_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

**Get Feature Text Conversion to Tokens**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv=CountVectorizer(lowercase =True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)

In [ ]:
x_train=cv.fit_transform(x_train)

In [ ]:
cv.get_feature_names_out()

array(['10 12', '10 bought', '10 fit', ..., 'yellow color', 'yoga pants',
       'zipper little'], dtype=object)

In [ ]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
x_test=cv.fit_transform(x_test)

In [ ]:
cv.get_feature_names_out()

array(['10 12', '10 dress', '10 fit', ..., 'years come', 'years old',
       'yoga pants'], dtype=object)

In [ ]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

**Get Model Train**

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
model=MultinomialNB()

In [ ]:
model.fit(x_train,y_train)

MultinomialNB()

**Get Model Prediction**

In [ ]:
y_pred =model.predict(x_test)

In [ ]:
y_pred.shape

(7046,)

In [ ]:
y_pred

array([1, 3, 5, ..., 5, 5, 5])

**Get Probability of Each Predicted class**

In [ ]:
model.predict_proba(x_test)

array([[0.41192504, 0.08714488, 0.33331872, 0.11047692, 0.05713443],
       [0.04140897, 0.04911105, 0.33814374, 0.30653697, 0.26479926],
       [0.0878448 , 0.05325155, 0.06196777, 0.06563966, 0.73129622],
       ...,
       [0.05098672, 0.01314522, 0.04610694, 0.1051662 , 0.78459492],
       [0.06221428, 0.0366794 , 0.03257317, 0.03523863, 0.83329452],
       [0.05549441, 0.03301911, 0.01202801, 0.24306642, 0.65639204]])

**Get Model Evaluation**

In [ ]:
from sklearn.metrics import  confusion_matrix,classification_report

In [ ]:
print(confusion_matrix(y_test,y_pred))

[[  33   19   47   39  115]
 [  57   44   73   92  204]
 [  92   82  126  200  361]
 [ 167  124  200  319  713]
 [ 398  227  357  762 2195]]


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.04      0.13      0.07       253
           2       0.09      0.09      0.09       470
           3       0.16      0.15      0.15       861
           4       0.23      0.21      0.22      1523
           5       0.61      0.56      0.58      3939

    accuracy                           0.39      7046
   macro avg       0.23      0.23      0.22      7046
weighted avg       0.42      0.39      0.40      7046



**Recategories Ratings as poor(0) and Good (1)**

In [ ]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

**Re-Rating as 1,2,3, as 0 and 4,5 as 1**

In [ ]:
df.replace({'Rating':{1:0,2:0,3:0,4:1,5:1}},inplace =True)

In [ ]:
y=df['Rating']

In [ ]:
x=df['Review Text']

**Train Test Split**

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size= 0.7,stratify= y, random_state= 2529)

In [ ]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

**Get Feature Text Conversion to Tokens**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv=CountVectorizer(lowercase= True,analyzer='word',ngram_range=(2,3),stop_words ='english',max_features=5000)

In [ ]:
x_train=cv.fit_transform(x_train)

In [ ]:
x_test=cv.fit_transform(x_test)

**Get Model Re-Train**

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
model=MultinomialNB()

In [ ]:
model.fit(x_train,y_train)

MultinomialNB()

**Get Model Prediction**

In [ ]:
y_pred =model.predict(x_test)

In [ ]:
y_pred.shape

(7046,)

In [ ]:
y_pred

array([1, 1, 1, ..., 1, 1, 1])

**Get Model Evaluation**

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report

In [ ]:
print(confusion_matrix(y_test, y_pred))

[[ 481 1102]
 [1012 4451]]


In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.32      0.30      0.31      1583
           1       0.80      0.81      0.81      5463

    accuracy                           0.70      7046
   macro avg       0.56      0.56      0.56      7046
weighted avg       0.69      0.70      0.70      7046

